### ISSUE TITLE
ground truth path is not found

### ISSUE THREAD

**Issue by kamilhabrych** [sakshamjindal/StereoVO-SFM#2]
Hi,

I've got this error while trying to start simulation:

```
ground truth path is not found.
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    main()
  File "main.py", line 26, in main
    dataset = KittiDataset(params.dataset.path)
  File "/home/ubuntu/Stereo-Visual-SLAM-Odometry/stereoVO/datasets/KITTI_Dataset.py", line 61, in __init__
    assert len(self.ground_truth) == len(self.left_image_paths)
TypeError: object of type 'NoneType' has no len()
```

Can you help me how to fix it or how files from KITTI's dataset should be organized and placed?

**Comment by sakshamjindal** [comment]
Thanks for pointing it out. Will work on uploading the datset in required form as soon as I get some time.

**Comment by kamilhabrych** [comment]
I figured it out, but now I've got a problem with:
`python3 main.py --config_path configs/params.yaml`

`Traceback (most recent call last):
  File "main.py", line 66, in <module>
    main()
  File "main.py", line 33, in main
    Plotter = SVO_Plot(figSize=(6, 4))
  File "/home/ubuntu/Stereo-Visual-SLAM-Odometry/stereoVO/utils/plot.py", line 19, in __init__
    fig1.canvas.set_window_title('Schematic Representation of Camera in 3D')
AttributeError: 'FigureCanvasQTAgg' object has no attribute 'set_window_title'`

**Comment by sakshamjindal** [comment]
This could be change in version of matplotlib that you might be using. I don't remember the version I was using. Perhaps, this could be helpful: https://stackoverflow.com/questions/75524228/getting-attributeerror-figurecanvasagg-object-has-no-attribute-set-window-ti.

Probably should work on upgrading the repo to reflect the required version packages.

**Comment by sakshamjindal** [comment]
If you have figured out the dataset setup that needs to be done and if the repo is helpful, can you PR to reflect in the README?

**Comment by kamilhabrych** [comment]
I will PR it later

**Comment by sakshamjindal** [comment]
So they deprecated `set_window_title`. Please have a look : https://github.com/raysect/source/issues/383

**Comment by kamilhabrych** [comment]
> Traceback (most recent call last): File "main.py", line 66, in <module> main() File "main.py", line 33, in main Plotter = SVO_Plot(figSize=(6, 4)) File "/home/ubuntu/Stereo-Visual-SLAM-Odometry/stereoVO/utils/plot.py", line 19, in __init__ fig1.canvas.set_window_title('Schematic Representation of Camera in 3D') AttributeError: 'FigureCanvasQTAgg' object has no attribute 'set_window_title'

Change from `fig1.canvas.set_window_title` to `fig1.suptitle` solved problem.

**Comment by kamilhabrych** [comment]
> ground truth path is not found.
> Traceback (most recent call last):
>   File "main.py", line 66, in <module>
>     main()
>   File "main.py", line 26, in main
>     dataset = KittiDataset(params.dataset.path)
>   File "/home/ubuntu/Stereo-Visual-SLAM-Odometry/stereoVO/datasets/KITTI_Dataset.py", line 61, in __init__
>     assert len(self.ground_truth) == len(self.left_image_paths)
> TypeError: object of type 'NoneType' has no len()

I put dataset and ground truth in: `/home/ubuntu/KITTI/KITTI_gray/dataset/sequences` and `/home/ubuntu/KITTI/KITTI_gray/dataset/poses/`

And I had to change 52th line of `/home/ubuntu/Stereo-Visual-SLAM-Odometry/stereoVO/datasets/KITTI_Dataset.py`:

From:
`self.gt_path = str(self.path.parents[3].joinpath('data_odometry_poses', 'dataset', 'poses', self.sequence_count + '.txt'))`

To:
`self.gt_path = str(self.path.parents[2].joinpath('dataset', 'poses', self.sequence_count + '.txt'))`
